### PR TITLE
Backend/owner message

### PR DESCRIPTION
**Pull request by GGolfz**
When the sender is the owner (graduate)
- Broadcast all text message
   + didn't handle command text message yet.
- Broadcast location message
- Broadcast Image message (not sure whether image send correctly or not)

### CODE REVIEW

**Comment by GGolfz** [comment]
image

**Review by thetkpark — APPROVED** [review]
LGTM

**Comment by thetkpark** [comment]
@GGolfz  Broadcasting an image works on Cloud Run

**Comment by GGolfz** [comment]
That’s great 🎉

**Pull request merged**
